### PR TITLE
special case group 0

### PR DESCRIPTION
**Pull request by vrothberg**
Special case the root user group to make it work in a container.

Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM 

Are we returning the UID names based on content in the container?

**Comment by vrothberg** [comment]
> Are we returning the UID names based on content in the container?

I hope so. Otherwise `os/user` has some peculiarities I don't know of.

**Comment by vrothberg** [comment]
> But is the code running inside of the containers mount namespace? Otherwise it is querying the /etc/password that is in the namespace of podman.

Yes, it is. I will look into this issue today and see what's going on.

**Pull request merged**
