### PR TITLE
Fix lint issues

### PR DESCRIPTION
**Pull request by vrothberg**
* catch errors of Setns()
* bump go versions

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan PTAL

Go 1.11.x and 1.12.x seem to be broken on Travis, so let's temporarily use go tip.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Should we be switching to golangci-lint?

**Comment by vrothberg** [comment]
> Should we be switching to golangci-lint?

SGTM :+1:

**Pull request merged**
