### PR TITLE
Add GHA CI

### PR DESCRIPTION
**Pull request by kolyshkin**
High-level overview:
* stop using sirupsen/logrus
* tune up Makefile (mostly by removing stuff not required by modern Go)
* add GHA CI jobs (golangci-lint, codespell, build, unit and integration tests)
* add a few more linters (errorlint, gofumpt) and fix warnings reported
* say goodbye to travis-ci

Please let me know if you find build/test with `-race` redundant, I can remove it.

### CODE REVIEW

**Comment by kolyshkin** [comment]
You can see the CI run at https://github.com/kolyshkin/psgo/pull/1/checks

**Review by vrothberg — APPROVED** [review]
LGTM, thanks for breaking it into easy to digest commits.

Out of curiosity: are you using psgo in another project?

@giuseppe PTAL

**Comment by kolyshkin** [comment]
> Out of curiosity: are you using psgo in another project?

Was looking into https://github.com/opencontainers/runc/pull/1852 and thinking maybe we can revive it.

**Comment by vrothberg** [comment]
> > Out of curiosity: are you using psgo in another project?
> 
> Was looking into [opencontainers/runc#1852](https://github.com/opencontainers/runc/pull/1852) and thinking maybe we can revive it.

Thanks, that's exciting!

**Comment by vrothberg** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
